import { Inter } from "next/font/google";
import "./layout.css";
import ReduxWrapper from "@components/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Solo Leveling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxWrapper>
          <div className="videoContainer">
            <video src={"./assets/videoBg.mp4"} autoPlay muted loop />
            <div className="overlay"></div>

            <div className="videoContainerItems">
              <div className="vci-1"></div>
              {/*  */}
              <div className="vci-2">{children}</div>
              {/*  */}
              <div className="vci-3"></div>
            </div>
          </div>
        </ReduxWrapper>
      </body>
    </html>
  );
}
